package controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;
import model.AeropuertoPrivado;
import model.AeropuertoPublico;

import java.net.URL;
import java.util.ResourceBundle;

import dao.AeropuertoDao;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.RadioButton;

public class EjercicioL_Anadir_AeropuertoController implements Initializable{
	@FXML
	private Label lblNTrabajadores;
	@FXML
	private RadioButton rbPublico;
	@FXML
	private RadioButton rbPrivado;
	@FXML
	private Button btnGuardar;
	@FXML
	private Button btnCancelar;
	@FXML
	private TextField txtNombre;
	@FXML
	private TextField txtPais;
	@FXML
	private TextField txtCiudad;
	@FXML
	private TextField txtCalle;
	@FXML
	private TextField txtNumero;
	@FXML
	private TextField txtInaguracion;
	@FXML
	private TextField txtCapacidad;
	@FXML
	private TextField txtFinanOsocios;
	@FXML
	private TextField txtNTrabajadores;
    @FXML
    private Label lblFinanciacion;

	// Event Listener on Button[#btnGuardar].onAction
	@FXML
	public void aniadirAeropuerto(ActionEvent event) {
		// TODO Autogenerated
		
		if(rbPrivado.isSelected()) {
			AeropuertoPrivado AP=new AeropuertoPrivado(0, txtNombre.getText(), txtPais.getText(), txtCiudad.getText(), txtCalle.getText(), Integer.parseInt(txtNumero.getText()), Integer.parseInt(txtInaguracion.getText()), Integer.parseInt(txtCapacidad.getText()), Integer.parseInt(txtFinanOsocios.getText()));
			AeropuertoDao aDao=new AeropuertoDao();
			aDao.aniadirAeropuertoPriv(AP);
		}else {
			AeropuertoPublico aPu=new AeropuertoPublico(0, txtNombre.getText(), txtPais.getText(), txtCiudad.getText(), txtCalle.getText(), Integer.parseInt(txtNumero.getText()), Integer.parseInt(txtInaguracion.getText()), Integer.parseInt(txtCapacidad.getText()), Double.parseDouble(txtFinanOsocios.getText()),Integer.parseInt(txtNTrabajadores.getText()));
			AeropuertoDao aDao=new AeropuertoDao();
			aDao.aniadirAeropuertoPu(aPu);
		}
		 Stage myStage = (Stage) this.btnGuardar.getScene().getWindow();
		 myStage.close();
	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void salir(ActionEvent event) {
		// TODO Autogenerated
		 Stage myStage = (Stage) this.btnGuardar.getScene().getWindow();
		 myStage.close();
	}
	  @FXML
	void cambiar(ActionEvent event) {
		  if(rbPrivado.isSelected()) {
			  lblNTrabajadores.setVisible(false);
			  lblFinanciacion.setText("Nº Socios");
			  txtNTrabajadores.setVisible(false);
			  
		  }else {
			  lblNTrabajadores.setVisible(true);
			  lblFinanciacion.setText("Financiacion");
			  txtNTrabajadores.setVisible(true);
			 
		  }
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		rbPrivado.setSelected(true);
		lblNTrabajadores.setVisible(false);
		lblFinanciacion.setText("Nº Socios");
		txtNTrabajadores.setVisible(false);
		
	}
}
