package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class SampleController {
	@FXML
	private Button btn;

	// Event Listener on Button[#btn].onAction
	@FXML
	public void abrirInforme(ActionEvent event) {
		// TODO Autogenerated
	}
}
